### ISSUE TITLE
IndexError in build_cgr during training process

### ISSUE THREAD

**Issue by caihaihua057200** [jugoetz/slap-platform-predict#2]
Description:

I encountered an issue while running the training script with the following command:
python run.py train --config config/config.yaml --data-path data/example_dataset.csv

Error Message:

The script fails with the following traceback:
Traceback (most recent call last):
  File "slap-platform-predict-master\src\data\grapher.py", line 108, in build_cgr
    products = MolFromSmiles(reaction_smiles.split(">>")[1])
IndexError: list index out of range
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\xtalpi\SLAM\slap-platform-predict-master\slap-platform-predict-master\run.py", line 134, in <module>
    args.func(args, hparams)
  File "D:\xtalpi\SLAM\slap-platform-predict-master\slap-platform-predict-master\src\run_experiment.py", line 29, in run_training
    data.process()
  File "D:\xtalpi\SLAM\slap-platform-predict-master\slap-platform-predict-master\src\data\dataloader.py", line 195, in process
    self.graphs = [
  File "D:\xtalpi\SLAM\slap-platform-predict-master\slap-platform-predict-master\src\data\dataloader.py", line 196, in <listcomp>
    build_cgr(
  File "D:\xtalpi\SLAM\slap-platform-predict-master\slap-platform-predict-master\src\data\grapher.py", line 114, in build_cgr
    raise ValueError(f"Could not build CGR for reaction: {reaction_smiles}") from e
ValueError: Could not build CGR for reaction: C[Si](C)(C)COCC1(/N=C/c2ccc(C(F)(F)F)cc2)CCOCC1

**Comment by jugoetz** [comment]
Looks like a SMILES input when the model expects a reactionSMILES. Try setting `reaction` to `false` in `config.yaml`

**Comment by caihaihua057200** [comment]
I am deeply grateful for the access to such an excellent open-source platform. I am looking to set the reaction to true. However, when I attempt to set the SMILES string to Nc1cc(Cl)ccc1[N+](=O)[O-]>>CC1(C)OB(c2ccc([N+](=O)[O-])c(N)c2)OC1(C)C, I encounter an issue at the point where `if a.HasProp("molAtomMapNumber"):` is executed, as it fails to recognize the molAtomMapNumber property for the atoms. Could you please advise on how to resolve this, or alternatively, provide a sample dataset where the reaction is set to true?
